name: Create Package

on: [push, workflow_dispatch]

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run Packaging Script
      working-directory: ${{github.workspace}}
      run:
        ./make_executable.sh MacOS-Universal

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Heavy-MacOS-Universal
        path: ./Heavy-MacOS-Universal

    - name: Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        draft: true
        files: Heavy-MacOS-Universal
