name: Create Package

on: [push, workflow_dispatch]

jobs:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
          - name: macOS
            os: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run Packaging Script
      working-directory: ${{github.workspace}}
      run:
        ./make_executable.sh ${{ matrix.os }}

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Heavy-MacOS-Universal
        path: ${{github.workspace}}/Heavy-MacOS-Universal

    - name: Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        draft: true
        files: Heavy-MacOS-Universal

    