name: Create Package

on: [push, workflow_dispatch]

jobs:
  build-macos:
    name: MacOS Univeral
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: brew install dfu-util

    - name: Run Packaging Script
      working-directory: ${{github.workspace}}
      run:
       CLEAR_INTL=1 ./build.sh

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Heavy-MacOS-Universal
        path: ${{github.workspace}}/Heavy

    - name: Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        draft: true
        files: Heavy-MacOS-Universal

  build-windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: Install Packages
        run: choco install python make -y

      - uses: actions/checkout@v3
        with:
          lfs: 'true'
          submodules: recursive

      - name: Run Packaging Script
        working-directory: ${{github.workspace}}
        run:
          ./build.bat

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Heavy-Win64
          path: ${{github.workspace}}/Heavy

      - name: Release Artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          draft: true
          files: Heavy-Win64

  build-linux:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container:
      image: debian
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    - name: Install Dependencies (apt)
      run: apt update && apt install -y git binutils python3 python3-pip curl tar gzip xz-utils make dfu-util patchelf libusb-dev build-essential rsync

    - uses: actions/checkout@v3
      with:
        submodules: recursive
      env:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    - name: Run Packaging Script
      working-directory: ${{github.workspace}}
      run:
        bash ./build.sh

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Heavy-${{ matrix.name }}
        path: ${{github.workspace}}/Heavy

    - name: Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        draft: true
        files: Heavy-Linux-x64

    
