name: Create Package

on: [push, workflow_dispatch]

jobs:
  build-macos:
    name: MacOS Univeral
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run Packaging Script
      working-directory: ${{github.workspace}}
      run:
        ./build.sh MacOS-Universal

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Heavy-MacOS-Universal
        path: ${{github.workspace}}/Heavy

    - name: Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        draft: true
        files: Heavy-MacOS-Universal

  build-windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: Install Packages
        run: choco install python -y

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Packaging Script
        working-directory: ${{github.workspace}}
        run:
          ./build.bat

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Heavy-Win64
          path: ${{github.workspace}}/Heavy

      - name: Release Artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          draft: true
          files: Heavy-Win64

  build-linux:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Ubuntu-22.04-x64
            os: ubuntu:22.04
            pacman: apt
          - name: Ubuntu-20.04-x64
            os: ubuntu:20.04
            pacman: apt
          - name: Debian-x64
            os: debian
            pacman: apt
          - name: Fedora-36-x64
            os: fedora:36
            pacman: dnf
          - name: Fedora-35-x64
            os: fedora:35
            pacman: dnf
          - name: Mageia-x64
            os: mageia
            pacman: dnf
          - name: OpenSUSE-Leap-x64
            os: opensuse/leap
            pacman: zypper
          - name: Arch-x64
            os: archlinux
            pacman: pacman

    steps:

    - name: Install Dependencies (dnf)
      if: ${{ matrix.pacman == 'dnf' }}
      run: dnf install -y git binutils python3 curl

    - name: Install Dependencies (apt)
      if: ${{ matrix.pacman == 'apt' }}
      run: apt update && apt install -y git binutils python3 python3-pip  curl

    - name: Install Dependencies (zypper)
      if: ${{ matrix.pacman == 'zypper' }}
      run: zypper refresh && zypper install -y git binutils python3 curl
    
    - name: Install Dependencies (pacman)
      if: ${{ matrix.pacman == 'pacman' }}
      run: pacman -Sy && pacman -S --noconfirm git binutils python3 curl && pacman --noconfirm -Syu

    - uses: actions/checkout@v3
      with:
        submodules: recursive
      env:
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    - name: Run Packaging Script
      working-directory: ${{github.workspace}}
      run:
        bash ./build.sh

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Heavy-${{ matrix.name }}
        path: ${{github.workspace}}/Heavy

    - name: Release Artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        draft: true
        files: Heavy-${{ matrix.name }}

    